### ISSUE TITLE
"Componentization" of Brook

### ISSUE THREAD

**Issue by silvioprog** [silvioprog/brookframework#101]
Hello,

After some requests, Brook will be componentized. In short words, after that, you can do in Lazarus IDE:

New ... | Brook | Brook Data Module Application

I.e., like FPWeb and FreeSpider.

And you will have some components in the pallet: BrookAction, BrookFCLCGIBroker, BrookForm etc.

It will not interfere in the present core. It will implemented apart, problably in other layer  out of the core.

@waldirpaim, @OsvaldoTCF @jbsolucoes

**Comment by Mario1234** [comment]
Once having Brook in the backend, perhaps a good approach to the frontend is the project JQUIF (JQuery UI Freepascal ) https://github.com/thierrydijoux/jquif, which consists in classes arround the jquery and jquery-ui libraries and plugins. The browser executes the JavaScript/AJAX code, and we program in Object Pascal as usual.
This way is going looking more "true web", than going looking the "similar to desktop" way (as Raudus, Kitto, UniGUI, etc.).

**Comment by herux** [comment]
thats very nice

**Comment by silvioprog** [comment]
This one was already done in Brook 4.0, and I probably will rewrite LazSolutions to use Brook 4.0, that will be the most fast HTTP server of all Pascal history!
