### ISSUE TITLE
Json and RestAction back on 3.0 Version

### ISSUE THREAD

**Issue by OsvaldoTCF** [silvioprog/brookframework#105]
For compatibility of the project page with version 3.0, we have the support RESTFul back, perhaps as a plugin, Broker, etc.
<b>JSon and RestAction</b> 

" JSON native support – JSON is widespred in the web for data exchange purposes. You will really appreciate Brooks' good JSON support.

 REST architecture support – REST is an architecture able to simplify and standardize data requests and replies. Brook is powerful even if you don't use REST – but you will want to use it."

**Comment by silvioprog** [comment]
It is already implemented in Brook 4.0, and it will be released soon.
