### ISSUE TITLE
Instruction for crosscompiling for Linux under Windows?

### ISSUE THREAD

**Issue by edwinyzh** [silvioprog/brookframework#106]
Hi,

According to the sourceforge download states, the majority of Lazarus users use the Windows version. On the other hand, the majority of the web servers in the world are teh Linux family.

So, is there an instruction for Lazarus Windows users to compile a Brook-powered project (CGI, for example) for deploying into a i-386-linux server? Thanks.

**Comment by silvioprog** [comment]
Nice. :-)
