### ISSUE TITLE
Support for HMVC: Calling requests internally

### ISSUE THREAD

**Issue by leledumbo** [silvioprog/brookframework#112]
The idea comes from Kohana (again). The core difference between MVC and HMVC is the ability for a controller (action) to call other action by means of creating request internally.

For instance, a typical web app might consist of a layout, a sidebar and a content. Layout calls sidebar and content, which in turn returns &lt;div&gt; for their respective content. Layout output (as HTML frontend) may periodically calls both to update its content via AJAX (not necessarily returns JSON, it's implementation details). Now what we need is to implement this "call" mechanism.

Suppose we have TBrookRequest capable of calling actions internally or any other http request to 3rd party web app. This class must be able to differentiate the request, whether it's an internal or external, by checking the parameter. Internal one should match a registered route. Sample call:

``` pascal
TBrookRequest.Call('/sidebar');
```

Assume the sidebar is streaming recent comments and eventually burdens server load, so it must be moved to another server. The only code change required is to replace above call to:

``` pascal
TBrookRequest.Call('http://sidebar/specific/server');
```

everything else remains the same. Without it, moving an action to another server will take much more code.

**Comment by leledumbo** [comment]
The support seems to be there already in BrookHTTPClient unit, but it's meant for generic request. Some things I want to confirm:

1. BrookFCLHttpClientBroker unit is only required to register the broker
2. TBrookHTTPClient is the one a user must use, supplying the registered broker name
3. Which approach do you prefer? A new TBrookRequest class in core or modify TBrookHTTPClient to support this feature?

**Comment by silvioprog** [comment]
You can choose the way that you keep the code as decoupled as possible. =)

**Comment by leledumbo** [comment]
Finally have some time to implement it. I decide to make it an external plugin to avoid cluttering the core. One thing that bugs me is: how can I call an action's method from another?

Digging in the code, I can see that each application broker calls `TBrookRouter.Service.Route(ARequest, AResponse)` which seems to be the starting point. However, I have difficulties in creating the ARequest and AResponse. Any existing function/method to create them?

**Comment by silvioprog** [comment]
Closing due to long time issue. If you have plan to implement this feature, please consider using the latest [Brook Tardigrade](https://github.com/silvioprog/brookframework/tree/tardigrade), that will be released in next days. It contains methods to override the default request/response initializers: https://github.com/silvioprog/brookframework/blob/tardigrade/Source/BrookHTTPServer.pas#L169 .

**Comment by silvioprog** [comment]
Edit: feel absolutely free to (re)issue to add (this or) new features! :smiley:
