### ISSUE TITLE
Métodos Lock e UnLock Implementados

### ISSUE THREAD

**Issue by almp1** [silvioprog/brookframework#115]
Olá Silvio, tudo bem ?
Estou usando o brook em um projeto e tive a necessidade de implementar os métodos Lock e Unlock
 como segue abaixo

BrookHttpUtils.pas
function BrookRequestMethodToStr(const AMethod: TBrookRequestMethod): string;
begin
  case AMethod of
    rmGet: Result := BROOK_HTTP_REQUEST_METHOD_GET;
    rmPost: Result := BROOK_HTTP_REQUEST_METHOD_POST;
    rmPut: Result := BROOK_HTTP_REQUEST_METHOD_PUT;
    rmDelete: Result := BROOK_HTTP_REQUEST_METHOD_DELETE;
    rmLock: Result := BROOK_HTTP_REQUEST_METHOD_LOCK;
    rmUnLock: Result := BROOK_HTTP_REQUEST_METHOD_UNLOCK;
    rmHead: Result := BROOK_HTTP_REQUEST_METHOD_HEAD;
    rmOptions: Result := BROOK_HTTP_REQUEST_METHOD_OPTIONS;
    rmTrace: Result := BROOK_HTTP_REQUEST_METHOD_TRACE;
  else
    Result := 'Unknown';
  end;
end;

BrookAction.pas
.
.
.
    procedure Delete; virtual;
    { Is triggered by a LOCK HTTP request method. }
    procedure Lock; virtual;
    { Is triggered by a UNLOK HTTP request method. }
    procedure UnLock; virtual;
    { Is triggered by a HEAD HTTP request method. }
    procedure Head; virtual;
.
.
.
.
procedure TBrookAction.Lock;
begin
  TBrookRouter.MethodNotAllowed(FTheResponse);
end;

procedure TBrookAction.UnLock;
begin
  TBrookRouter.MethodNotAllowed(FTheResponse);
end;
.
.
.

BrookHttpConsts.pas
.
.
.
  BROOK_HTTP_REQUEST_METHOD_MKCOL = 'MKCOL';
  BROOK_HTTP_REQUEST_METHOD_TRACE = 'TRACE';
  BROOK_HTTP_REQUEST_METHOD_LOCK = 'LOCK';
  BROOK_HTTP_REQUEST_METHOD_UNLOCK = 'UNLOCK';
  { Some header fields }
.
.
.

BrookUtils.pas
.
.
.
  { Defines an enumerator to represent the HTTP request methods. }
  TBrookRequestMethod = (
    rmUnknown, rmAll, rmGet, rmPost, rmPut, rmDelete, rmHead, rmOptions, rmTrace,
    rmLock, rmUnLock
  );
.
.
.

Se for possível deixar disponível para as próximas atualizações, acredito que seja de grande utilidade,

Abraços e sucesso

**Comment by silvioprog** [comment]
Olá @almp1 , parabéns pelo progresso com Brook e obrigado por compartilhar sua ideia! =)

A Brook 4.0 está no forno, logo logo teremos novidades, e a customização dos verbos HTTP será uma delas.

Abração!
