### ISSUE TITLE
How to download file?

### ISSUE THREAD

**Issue by shariful2011** [silvioprog/brookframework#117]
Upload is there but how to download a file using Brookframework? Any guide will be helpful.

**Comment by silvioprog** [comment]
Is very easy to download a file, so you should do it directly like this code below:

```pascal
uses
  fphttpclient, LCLIntf;

procedure TForm1.Button1Click(Sender: TObject);
const
  FILE_NAME = 'humans.txt';
var
  VFileName: TFileName;
begin
  VFileName := GetTempDir + FILE_NAME;
  TFPHTTPClient.SimpleGet('http://www.google.com/' + FILE_NAME, VFileName);
  OpenDocument(VFileName)
end;
```

The Brook 3.0 HTTP clients was done before this FCL feature above, but Brook 4.0 will reimplement it, allowing to get content/files even from fast protocols like `SPDY` and `HTTP 2.0`.
