### ISSUE TITLE
Upload and Download by URI

### ISSUE THREAD

**Issue by shariful2011** [silvioprog/brookframework#118]
I need to upload and download file by URI such as http://myserver/<filename>. This filename will be upload by one BrookAction and in another BrookAction download will be done. Is it possible? I am using Embedded daemon server. From this server there will be 2 methods upload & download, client can upload & download file.

**Comment by shariful2011** [comment]
No one here to answer!

**Comment by silvioprog** [comment]
Hello. You can send your file(s) just using `TBrookHTTPClient` or something like this, and so you can get your file(s) via `TBrookAction.Files` property, that is a list containing all uplodaded files.

**Comment by shariful2011** [comment]
Will it be in Get or Post method?

**Comment by silvioprog** [comment]
Only via `POST/PUT`. You can't send a upload via `GET` method, this is a HTTP standard. =/

**Comment by shariful2011** [comment]
Can you please provide some source code help on how to implement?

**Comment by shariful2011** [comment]
My client will not be based on brook it will be php. So all my code will be in server side. I will just provide the binary for download and json for upload.

**Comment by shariful2011** [comment]
This is what I did nothing is working:
I set vfilename and vfile as private
procedure TPut_File.Get;
begin
  vfilename := Params.Values['filename'];
  vfile := Params.Values['file'];
  Write({$i head.inc}, [vSettings.BaseURL + '/put_file?filename=' + vfilename + '&file=' + vfile]);
end;
procedure TPut_File.Post;
var
  ContentType: String;
  VHttp: TBrookHTTPDef;
  js : TJSONObject;
begin
  vfilename := Params.Values['filename'];
  vfile := Params.Values['file'];
  Files.Add;
  Files[0].FileName := vfile;
  st := TMemoryStream.Create;
  st.WriteBuffer(Files[0], Files[0].Size);
  st.Seek(0, st.Size);
  ContentType := MimeTypes.GetMimeExtensions(ExtractFileExt(vfile));
  VClient := TBrookHTTPClient.Create('fclweb');
  try
    VClient.Prepare(VHttp);
    VHttp.Url := vSettings.BaseURL + '/put_file';//?filename=' + vfilename + '&file=' + vfile;
    VHttp.Method := BROOK_HTTP_REQUEST_METHOD_POST;
    VHttp.ContentType := ContentType;
    VHttp.PostFile(VHttp.Url, vfilename, vfile, st);// this is where debugger stuck

    js := TJSONObject.Create;
    js.Add('file', vfile);
    js.Add('content', ContentType);
    js.Add('file size', Files.Count);
    js.Add('ext', ExtractFileExt(vfile));
    js.Add('filename', Files[0].FileName);
    write(js.AsJSON);
  finally
    VHttp.Free;
    VClient.Free;
    js.Free;
    st.Free;
  end;
end;
my head.inc as following:
'<!DOCTYPE HTML>' + LF +
'<html lang="en-US">' + LF +
'<head>' + LF +
'	<meta charset="UTF-8">' + LF +
'</head>' + LF +
'<body onload="document.put_file.submit()">' + LF +
'	<form action="%s" enctype="multipart/form-data" method="post" name="put_file">' + LF +
'		<p><input type="submit" style="display:none"/></p>' + LF +
'	</form>' + LF +
'</body>' + LF +
'</html>'

Can you please help?

**Comment by shariful2011** [comment]
head.inc
'<!DOCTYPE HTML>' + LF +
'<html lang="en-US">' + LF +
'<head>' + LF +
'	<meta charset="UTF-8">' + LF +
'</head>' + LF +
'<body onload="document.put_file.submit()">' + LF +
'	<form action="%s" enctype="multipart/form-data" method="post" name="put_file">' + LF +
'		<p><input type="submit" style="display:none"/></p>' + LF +
'	</form>' + LF +
'</body>' + LF +
'</html>'

**Comment by silvioprog** [comment]
Hm... I'm confused... are you sending a file from a PHP client to Brook server? If so, you can isolate your code to explain it better, and showing the PHP code on the client side. I can send a small demo, but firstly I need to see how are you doing.

**Comment by shariful2011** [comment]
My server will upload and download files by mainly PHP. I am not the part to produce the php client, my only part is to create Brook based server hosted in Linux. The main part is it will put and get file by url like http://localhost:port/put_file?filename=&file= for upload and http://localhost:port/get_file?filename= for downloading.

**Comment by shariful2011** [comment]
Mainly it will be Embedded daemon server for Linux.

**Comment by shariful2011** [comment]
Do you understand my requirement? Please help.

**Comment by shariful2011** [comment]
Can you please send me a small demo?

**Comment by shariful2011** [comment]
No response or demo yet.

**Comment by silvioprog** [comment]
I can't understand your last code. :-/ But to upload a file and get it in backend is very easy:

1. your client should use some API like this:

```pascal
TFPHTTPClient.SimpleFileFormPost('<your-url>', 'some-field-name', 'your-file.txt', YourFileStream);
```

2. and in your backend you can get the uploaded file via `TBrookAction.Files` property:

```pascal
procedure TYourAction.Post;
begin
  Files.First.SaveToFile('your-uploaded-file.txt');
end;
```

**Comment by shariful2011** [comment]
Files.First.SaveToFile does not exist

**Comment by silvioprog** [comment]
So use Files[0].SaveToFile instead.
