### ISSUE TITLE
TBrookRouterHandler doesn't link to TBrookRouter

### ISSUE THREAD

**Issue by leledumbo** [silvioprog/brookframework#120]
I'm testing brook components. So far, TBrookMiddlewareHandler works great by registering itself before / after action execution. However, TBrookRouterHandler doesn't seem to register itself to the listed events. I put a breakpoint in TBrookRouter.MatchPattern and:

``` pascal
if Assigned(FBeforeMatchPattern) then
```

keeps returning `false` even though I have filled the BeforeMatchPattern events in object inspector. I need to use the component to redirect empty path info to /.

**Comment by silvioprog** [comment]
Hum... I can't understand even with the explanation. Can you send a small demo showing the problem? I use middleware in an application that the user is redirected to the login page if he is not logged.

**Comment by leledumbo** [comment]
[brookroutertest.tar.gz.pdf](https://github.com/silvioprog/brookframework/files/25066/brookroutertest.tar.gz.pdf)

remove the .pdf extension (damn github)

**Comment by silvioprog** [comment]
I downloaded it. =)

I'll debug this problem tonight ...

**Comment by silvioprog** [comment]
I can't detect if it is a problem in Brook sources or in the compiler. :-(

I'm going to try it again...

**Comment by silvioprog** [comment]
Fixed in trunk. Thanks for reporting! :-)
