### ISSUE TITLE
SSL option available?

### ISSUE THREAD

**Issue by shariful2011** [silvioprog/brookframework#122]
Is SSL can be use?

**Comment by leledumbo** [comment]
It depends on your web server. If you use embedded web server (which doesn't support https yet), you can always use another web server (which supports https) to act as a proxy. That's what I do on our system.

**Comment by shariful2011** [comment]
I am testing locally with https but I can't get response. Do I need SSL Certificate (self certified) for this on locally. In production it will be Certified by CA. Also I am developing a embedded server.

**Comment by silvioprog** [comment]
Hi @shariful2011 , the Brook Tardigrade has builtin TLS support based on GnuTLS. This version will be release in next days, but it is already available at: https://github.com/silvioprog/brookframework/tree/tardigrade .
