### ISSUE TITLE
Cannot install brookrt.lpk 1.9.9 on Lazarus 1.6 on Mac OS X

### ISSUE THREAD

**Issue by tuppa** [silvioprog/brookframework#123]
Tested on El Capitan, cannot compile package due to CustFCGI not found.

> Compile package BrookRT 3.9.9: Exit code 256, Errors: 1
> brookfclfcgibroker.pas(23,12) Fatal: Cannot find CustFCGI used by BrookFCLFCGIBroker of package BrookRT.

**Comment by silvioprog** [comment]
It seems that El Capitan doesn't have the CustFCGI unit. Can you add an IFDEF fixing it and send a patch for us? Thanks!

**Comment by tuppa** [comment]
I managed to work around it by opening the BrookRT package while I had the BrookEX package open, and removed brookfclfcgibroker.pas from the BrookRT package window.

Adding IFDEFs to exclude CustFCGI unit from brookfclfcgibroker.pas didn't work as CustFCGI was referenced in many places in the file.

**Comment by MFernstrom** [comment]
I'm having the same issue, can't install Brook due to not having CustFCGI.

I'm on El Capitan

**Comment by reminder2k1** [comment]
Just added fcl-web source path on BrookRT Search Path on Options.

<img width="554" alt="screen shot 2017-03-25 at 4 43 06 pm" src="https://cloud.githubusercontent.com/assets/967982/24321242/26e4d302-117a-11e7-96ad-3e116dacd907.png">

**Comment by MFernstrom** [comment]
I added the cfl-web/src/base to path and now it compiles, but when trying to install I get this error:
turbopoweripro.pas(10,34) Fatal: Cannot find Iphttpbroker used by TurboPowerIPro, incompatible ppu=/Developer/lazarus/components/turbopower_ipro/units/i386-darwin/carbon/iphttpbroker.ppu, package TurboPowerIPro

**Comment by MFernstrom** [comment]
If I uninstall TurboPower, I can install Brook 3 and rebuild Lazarus just fine.

**Comment by silvioprog** [comment]
Closing since it was already solved. Thanks for reporting dudes! (I would like to test Brook Tardigrade on MAC :-) )
