### ISSUE TITLE
Base64 receiving from server takes too much time.

### ISSUE THREAD

**Issue by shariful2011** [silvioprog/brookframework#124]
I am trying to send base64 for image to client which taking too much times. I am using TRestClient in Delphi to get the base64 and decode it to TBitmap. Also in browser if I put the server url it's taking too much time to load in browser. Below is my code:
fFile is reside in server which is a png file.  
fbase64 := FileToBase64(ImagePath +  IncludeLeadingPathDelimiter('') + fFile);
js := TJSonObject.Create(['file', fbase64]);
Write(js.AsJSON);
js.free;

How to speed up in loading the base64?

**Comment by silvioprog** [comment]
What is `FileToBase64`?

**Comment by shariful2011** [comment]
function FileToBase64(const AFileName: TFileName): string;
var
  VFile: TFileStream;
  VStream: TStringStream;
begin
  VFile := TFileStream.Create(AFileName, fmOpenRead or fmShareDenyWrite);
  VStream := TStringStream.Create('');
  try
    with TBase64EncodingStream.Create(VStream) do
      try
        CopyFrom(VFile, VFile.Size);
      finally
        Free;
      end;
    Result := VStream.DataString;
  finally
    VStream.Free;
    VFile.free;
  end;
end;

**Comment by silvioprog** [comment]
Which line is slow (1, 2, 3 or 4)?

```pascal
1. fbase64 := FileToBase64(ImagePath + IncludeLeadingPathDelimiter('') + fFile);
2. js := TJSonObject.Create(['file', fbase64]);
3. Write(js.AsJSON);
4. js.free;
```

It seems that the `FileToBase64` is fast, because it load the buffer by demand (`.CopyFrom()`), but you can try to change its line code from:

```pascal
...
CopyFrom(VFile, VFile.Size);
...
```

to:

```pascal
...
CopyFrom(VFile, 0);
...
```

**Comment by silvioprog** [comment]
Hi @shariful2011 , closing due to long time issue, but feel free to reissue if the problem persists.
