### ISSUE TITLE
Redeploy Brook app on a production server

### ISSUE THREAD

**Issue by Mario1234** [silvioprog/brookframework#126]
Sorry, this is not an issue. Is a question more suited for a forum, but I couldn't find a forum.
The question is: Which would be the best way to re-deploy Brook app on a production Linux server ?
What I already do is kill -15 the running app and then start it again, but this is kind of "rude" for the web users.
Is there a way to know which sessions are on-course ? A way to signal the app to Terminate in Pascal code? A way to keep open sessions (as in GlassFish redeploy with keepSessions=true) ? 
Is better to have a single executable or many ?
Thanks in advance,
Mario

**Comment by silvioprog** [comment]
Are you using the stand-alone server?

**Comment by Mario1234** [comment]
Oh, yes, I forget to mention this fact. I'm using the stand-alone server (embedded server), in Brokers.pas it uses BrookFCLHttpAppBroker.
I did some trials with CGI and Apache, and FCGI and Apache (and even tried FCGI with GlassFish). But the best performance and less troubles was with the embedded server, so it is my choice.

**Comment by silvioprog** [comment]
Hum... I don't know how the FCL HTTP server treats signals, but I think you need do something like this. Currently, Brook 4 (that will be released soon) has an option `myserver -s stop`, that gracefully stops the server to receive new connections, and waits the end of active connections. The shutdown and boot is very fast, something like 1/3 s, nice for redeploy apps in production. My suggestion is: try something like signals, and wait the new stand-alone event-driven Brook HTTP(S) server, it will be compilable in FPC and Delphi.

**Comment by Mario1234** [comment]
Thanks Silvio. I will be waiting for Brook 4.
