### ISSUE TITLE
daemon httpserver

### ISSUE THREAD

**Issue by almp1** [silvioprog/brookframework#132]
Olá Silvio,
Tudo bem?

Tenho usado o Brook framework em um projeto CGI, onde o ambiente é Linux64+Apache+(CGIs Brook) :) para este projeto tenho usado como base o TBrookAction, apenas runtime, sem webmodule

O projeto esta em produção a mais de um ano. 

Agora eu precisava implementar um serviço deamon+http+webserver. E vejo que o Brook da suporte para isso, basta criarmos um projeto do tipo Embedded deamon server. 

A minha duvida é sobre o uso de componentes visuais, por exemplo, se eu criar a aplicação com TBrookDataModule é possível usar um fortes reports ? 

E quando eu crio o projeto usando o TBrookDataModule, eu não consigo adicionar rotas, recebo este erro "TBrookRouter: No route registered." Procurei por algum exemplo de como implementar, mas não encontrei. 

Será que você poderia me dar alguma dica de como prosseguir com isso ?

Grande abraço,

**Comment by silvioprog** [comment]
Olá André, tudo tranks?! :-)

Fico feliz em saber que está usando Brook em produção e já a tanto tempo. Seria até uma boa a gente ter uma página "Quem está usando Brook?" ou "Casos de sucesso", assim o pessoal poderia compartilhar um pouco suas experiências com o framework.

Então, tempos atrás alguém pediu um exemplo para iniciar e finalizar o server da Brook em um formulário LCL com botões "Start/Stop" e deu certo, daí, creio que seja possível criar uma aplicação [L/V]CL com Fortes + Brook. Ou, uma segunda opção, que seria usando o widget nogui, mas este é especificamente para Lazarus.

Sobre o erro, teria como mostrar um passo a passo de como você fez? Se for bug com certeza a gente resolve.

Aproveitando o embalo, fique atento na comunidade da Brook lá no G+, pois está bem pertinho de sair um alpha da tão esperada versão 4. :-)

Abração!

**Comment by almp1** [comment]
Olá Silvio, td bem !? :)

Obrigado pela resposta,

Fico feliz em saber que está usando Brook em produção e já a tanto tempo.
Seria até uma boa a gente ter uma página "Quem está usando Brook?" ou
"Casos de sucesso", assim o pessoal poderia compartilhar um pouco suas
experiências com o framework.
Muito legal sua ideia, conte comigo qdo for fazer isso, teremos muito
prazer em compartilhar nossas experiencias com o Brook

Então, tempos atrás alguém pediu um exemplo para iniciar e finalizar o
server da Brook em um formulário LCL com botões "Start/Stop" e deu certo,
daí, creio que seja possível criar uma aplicação [L/V]CL com Fortes +
Brook. Ou, uma segunda opção, que seria usando o widget nogui, mas este é
especificamente para Lazarus.
Nosso objetivo é fazer um serviço, que possa ser instalado no windows, mas
este serviço deveria executar um PDF feito em Fortes, por isso o uso do
BrookDataModule. Sim estamos usando Lazarus e deixo o Nogui ativado

Sobre o erro, teria como mostrar um passo a passo de como você fez? Se for
bug com certeza a gente resolve.
Acredito não ser um erro, mas uma falha na minha implementação. Estou
criando um "Embedded daemon server" e escolho Designtime (with data
module). Criei uma procedure Get, como se fosse um BrookAction, mas acho
que o conceito do Embedded daemon server é bem diferente de um CGI
A mensagem que recebo é
500 - Internal server error

TBrookRouter: No route registered.
 por isso gostaria de um exemplo

Aproveitando o embalo, fique atento na comunidade da Brook lá no G+, pois
está bem pertinho de sair um alpha da tão esperada versão 4. :-)
Me inscrevi na comunidade do Brook no G+ e vou acompanhar e contribuir no
que for preciso conforme nossas possibilidades :)

Abraços,




Em 21 de março de 2017 12:02, Silvio Clecio <notifications@github.com>
escreveu:

**Comment by silvioprog** [comment]
Show de bola! :-)

Pensei aqui numa forma da gente descobrir o que é: cria um pequeno exemplo isolando só essa parte do erro, daí abro aqui no meu Lazarus e faço o debug para checar o que ocorre.

Abração!

**Comment by almp1** [comment]
Olá Silvio

Você vai perceber que no teste1 eu não consegui sair da inicialização, mas
no que você puder me ajudar eu agradeço.

No teste2 eu usei um exemplo do próprio Brook com sucesso mas sem o
DataMudule. Em linhas gerais, eu gostaria de fazer o que fiz no teste2 só
que no teste1 :)

Abraços,



Em 22 de março de 2017 13:46, Silvio Clecio <notifications@github.com>
escreveu:

**Comment by silvioprog** [comment]
Algum link para baixá-los? :-)

**Comment by almp1** [comment]
Opa

Acho que os anexos não foram :)

https://www.dropbox.com/s/x22dgjyxraniwda/teste1.zip?dl=0
https://www.dropbox.com/s/wqvtcnpwv6ky3eh/teste2.zip?dl=0

Abraços,


2017-03-22 15:12 GMT-03:00 Silvio Clecio <notifications@github.com>:

**Comment by almp1** [comment]
Bom dia Silvio, td bem?

Como eu havia dito, era uma falha na minha implementação. Mesmo depois de
tanto tempo usando o Brook, eu nunca havia usado o assistente criando um
projeto do tipo Fast/CGI. É incrível :)

Usei o assistente e consegui implementar um BrookFCLHttpDaemonBroker da
forma que precisávamos.

Obrigado, fico a disposição.

Grande abraço,


Em 22 de março de 2017 15:28, André Medeiros <
andremedeiros@asolutions.com.br> escreveu:

**Comment by silvioprog** [comment]
Show de bola André! :-) Como o problema foi resolvido vou marcar o issue como fechado, mas sinta-se a vontade caso precise reabri-lo. Abração!
