### ISSUE TITLE
How to read request custom header

### ISSUE THREAD

**Issue by 2keda** [silvioprog/brookframework#135]
hello, i'm new with brook, 

when client send request with modified header, like 
SomeHeader=SomeValue.

how can i get/read SomeHeader=SomeValue request header with brook, i used HttpRequest.GetCustomHeader('SomeHeader') but i got empty result. 

oh, and how to get/read client request body

Thanks.

**Comment by leledumbo** [comment]
Headers are sent with `:` as key-value separator, not `=`.

**Comment by silvioprog** [comment]
Closing due to no more activities on the issue. Please feel free to reissue if the problem persists.
