### ISSUE TITLE
BrookStaticFileRegisterDirectory returns blank pages when files are requested

### ISSUE THREAD

**Issue by MFernstrom** [silvioprog/brookframework#136]
Running Brook 3 on OSX El Capitan.

When I register a static folder and try to access a file in the browser, I just get a blank white page, no error messages.

I'm using the demo as base:
`BrookStaticFileRegisterDirectory('/css/', PublicHTMLDir + 'css');
BrookStaticFileRegisterDirectory('/js/', PublicHTMLDir + 'js');
BrookStaticFileRegisterDirectory('/images/', PublicHTMLDir + 'images');`

I also noticed that MimeTypes.LoadFromFile would not work unless I gave it the full path such as
`MimeTypes.LoadFromFile(IncludeTrailingPathDelimiter(ExtractFilePath(ParamStr(0)))+'mime.types');`

Not sure if the two are related.

**Comment by MFernstrom** [comment]
After some digging, I figured it out.

In BrookStaticFileBroker procedure TStaticFileAction.Get;

If I add this line before VFilePath, it works just fine
`VPathInfo := '/' + VPathInfo;`

The first / is missing, which is there when registering the path, so it just comes up blank.

**Comment by silvioprog** [comment]
Hi @MFernstrom , closing due to old issue. Please open a new issue if the problem persists.
