### ISSUE TITLE
Brook and Amazon S3

### ISSUE THREAD

**Issue by silvioprog** [silvioprog/brookframework#14]
It would be interesting to Brook have a broker or plugin implementing the [Amazon's S3 service](http://aws.amazon.com/s3/).

**Comment by openand-inc** [comment]
Thank you for resurrecting the Lazarus. Please also let it enter the record the request for:

- Anycast DNS 
- Anycast HTTP
- Atomic buffers, similar to Spanner
- Multiplicative effect Async buffers, ala Xmap

Also the app framework on Delphi is ugly to start with. 

The app development version of Lazarus ;) needs a set of components and an interface like Xamarin.
