### ISSUE TITLE
EAccessViolation error

### ISSUE THREAD

**Issue by dingo1313** [silvioprog/brookframework#142]
Compiling the default handler demo (version 3 framework) the action executes fine but in the apache2 error.log I get the following error:

> An unhandled exception occurred at $00000000004A0D01:
> EAccessViolation: Access violation

Using Debian 8 AMD64 with Apache 2.4. Apache2 has all rights to the cgi-bin as far as i can see.

**Comment by leledumbo** [comment]
That exception is from the compiled binary, not apache. Recompile with -glh (your app and the framework) to get a stacktrace.

**Comment by dingo1313** [comment]
Compiling from command line with fpc cannot find the framework. From lazarus just compiles and running it gives besides the expected Internal server error in html this message:

An unhandled exception occurred at $00000000004A0D01:
EAccessViolation: Access violation
  $00000000004A0D01
  $000000000041374C
  $0000000000417067

Which of course does not say me anything.

**Comment by leledumbo** [comment]
> Compiling from command line with fpc cannot find the framework

Pass -Fu to the framework's compiled units directory. Or copy parameters from Project Options->Show Options.

> From lazarus just compiles and running it gives besides the expected Internal server error in html this message

This is with -glh activated?

**Comment by dingo1313** [comment]
That worked.

Heap dump by heaptrc unit
3334 memory blocks allocated : 396680/396968
3325 memory blocks freed     : 395847/396128
9 unfreed memory blocks : 833
True heap size : 262144
True free heap : 259872
Should be : 260152
Call trace for block $00007F45C36080C0 size 128
  $0000000000413D11
  $000000000041374C
  $0000000000417067
Call trace for block $00007F45C3640C00 size 40
  $0000000000413D11
  $000000000041374C
  $0000000000417067
  $000000000048F744  REGISTER,  line 354 of ../core/brookaction.pas
  $000000000048F68A  REGISTER,  line 344 of ../core/brookaction.pas
  $0000000000429C2B  UNIT1_$$_init$,  line 44 of unit1.pas
  $0000000000416FCD
Call trace for block $00007F45C3640B40 size 24
  $000000000041374C
  $0000000000417067
Call trace for block $00007F45C36412C0 size 41
  $00000000004B1556  CREATEREQUEST,  line 205 of ../brokers/brookfclcgibroker.pas
  $00000000004B2B8C
  $00000000004007FB  main,  line 9 of cgi1.lpr
Call trace for block $00007F45C3641080 size 32
  $00000000004A4058
  $00000000004B17B5  BROOKFCLCGIBROKER_$$_init$,  line 231 of ../brokers/brookfclcgibroker.pas
  $0000000000416FCD
Call trace for block $00007F45C3640FC0 size 24
  $00000000004A4058
  $00000000004B17B5  BROOKFCLCGIBROKER_$$_init$,  line 231 of ../brokers/brookfclcgibroker.pas
  $0000000000416FCD
Call trace for block $00007F45C36180C0 size 320
  $00000000004A4058
  $00000000004B17B5  BROOKFCLCGIBROKER_$$_init$,  line 231 of ../brokers/brookfclcgibroker.pas
  $0000000000416FCD
Call trace for block $00007F45C3699220 size 184
  $00000000004B17B5  BROOKFCLCGIBROKER_$$_init$,  line 231 of ../brokers/brookfclcgibroker.pas
  $0000000000416FCD
Call trace for block $00007F45C3640F00 size 40
  $00000000004B17B5  BROOKFCLCGIBROKER_$$_init$,  line 231 of ../brokers/brookfclcgibroker.pas



line 344 = Register(APattern, rmAll, ADefault);
line 354 = TBrookRouter.Service.Routes.Add(Self, LowerCase(APattern), AMethod, ADefault);


line 205 = ApplicationURL := TBrookRouter.RootUrl;
line 231 = BrookRegisterApp(TBrookApplication.Create);

**Comment by leledumbo** [comment]
Sorry, please reduce to just -gl. I should've not care about memory leaks as we're talking about access violation here.

**Comment by dingo1313** [comment]
With -gl only the stacktrace remains nothing else no line numbers, nothing.

**Comment by leledumbo** [comment]
Hmm... it should not, unless the exception is really raised from RTL/FCL-web level, in which you must rebuild them with -gl as well to get deeper stacktrace. It's a really rare situation since both are well tested packages. There has to be something unique about your environment.

**Comment by dingo1313** [comment]
Then i have to look for another solution then Lazarus/FPC, too bad.
