### ISSUE TITLE
Register ADefault doesn't work when using BrookStaticFileRegisterDirectory

### ISSUE THREAD

**Issue by MFernstrom** [silvioprog/brookframework#145]
I've no idea why this is happening yet but here it is:

If I have an action TMyAction.Register('/start', true); but only if I don't use BrookStaticFileRegisterDirectory.

Using BrookStaticFileRegisterDirectory causes a non-matching path to throw a 404 instead of redirecting to the default path.

Easy to test:

Create an action, set it as default.
Make sure it works when visiting a non-matching path.

Then add a static file register and try again.

**Comment by silvioprog** [comment]
Hi @MFernstrom , just change `'/start'` to `/` that solves the problem. :-)

Thanks for reporting!
