### ISSUE TITLE
How can I send to the client a static file in the root directory with the app?

### ISSUE THREAD

**Issue by Al-Muhandis** [silvioprog/brookframework#146]
I use directory with static files (css, js and so on) by means BrookStaticFileBroker. But if I must to place static file in the root url? For example, robots.txt. With the condition that in Apache set alias from the root url to the app in the cgi-bin folder.

**Comment by Al-Muhandis** [comment]
Thank very much... I tried this option, but the application apparently gets stuck in a loop (Out of memory HTTP 500) because of alias in the Apache settings `ScriptAlias / /var/www/user1/data/www/mysite_example.com/cgi-bin/index.fcgi/`

**Comment by leledumbo** [comment]
Well... don't use that alias then, let the application handle it.

**Comment by Al-Muhandis** [comment]
Thank you

**Comment by silvioprog** [comment]
Closing since the problem was fixed. Thanks for reporting @Al-Muhandis !
