### ISSUE TITLE
I can't find the documentation

### ISSUE THREAD

**Issue by zoran-vucenovic** [silvioprog/brookframework#148]
Hello,
I can't find any documentation. The front page links to https://brookframework.org/doc/index.html (html format) and https://brookframework.org/doc/brookframework-ref.pdf (pdf format), but both links does not work.

Can you please fix these links, or can the documentation be found somewhere else?

**Comment by silvioprog** [comment]
Hi @zoran-vucenovic .

Now you can download it in [PDF](https://github.com/silvioprog/brookframework/releases/download/v3.0.0/brookframework-ref.pdf) or [HTML](https://github.com/silvioprog/brookframework/releases/download/v3.0.0/brookframework.html-ref.zip).

Thanks for reporting!
