### ISSUE TITLE
Telegram plugin for brookframework

### ISSUE THREAD

**Issue by Al-Muhandis** [silvioprog/brookframework#150]
It's probably not a question. It's just that if someone suddenly needs to create a telegram bot to their online service built on a brook framework, this library ( https://github.com/Al-Muhandis/brook-telegram/ ) might be useful or even he will want to join the development. Once again, thank you for your framework!

**Comment by silvioprog** [comment]
Great work! :+1: 

I'm not very familiar with Telegram's API, so I'm not sure if it is something related to client-side or server-side, or both. I need to test it when I have a free time. :-) Anyway, as server-side, it can be implemented in Brook4REST too; as client-side, it we need to wait the Brook4cURL be release.

**Comment by Al-Muhandis** [comment]
[Telegram] bots - automatic helpers in the telegram messenger chat. Telegram bot API is useful for creating telegram bot.
In general, this is implemented on the server side. The endpoint of the API is the telegram server. As a client - any user of Telegram messenger, who will send commands and requests to the bot associated with our application, in particular, based on brookframework. A telegram server can communicate with a bot through a webhook or through long polling. In the above plugin, the webhook method is used (the address we defined on our site, for example, https://someexample.com/cgi-bin/secrettoken). It is also possible to work through long polling, but I have not yet realized it. In the case of long polling, you can make bots without webhook, that is, you do not need a site, you can run even on a desktop.

**Comment by Al-Muhandis** [comment]
> it we need to wait the Brook4cURL be release.
I just used TFPHTTPClient to access another server (In particular https://api.telegram.org/bot%bot-token%/ ) and everything worked... If I correctly understood the purpose of Brook4cURL

**Comment by silvioprog** [comment]
Oops, I meant "... we need to wait the Brook4cURL be released ...". ^^'

Thanks for sharing the info regarding Telegram bots. It seems a great feature and it was added in my whishlist for future testings.

> I just used TFPHTTPClient to access another server (In particular https://api.telegram.org/bot%bot-token%/ ) and everything worked... If I correctly understood the purpose of Brook4cURL

Brook4cURL will be a small HTTP/websocket library, so your Telegram plugin can be used anywhere: any compiler (FPC/Delphi/GCC etc.) and any target (Linux/ARM, Windows, MacOS etc.). :-)

As soon as I have a free time I'll check your Telegram plugin and try it with Brook4REST library too.

**Comment by Al-Muhandis** [comment]
> so your Telegram plugin can be used anywhere: any compiler (FPC/Delphi/GCC etc.)
> 

Hmmm... Cool, I did not think it was possible

**Comment by silvioprog** [comment]
Please let me know if you implemented it. Closing but feel free to reissue if necessary! :smiley:

**Comment by Al-Muhandis** [comment]
I have already implemented it for a long time, I use this plugin/unit in several of my telegram bots, implemented with the help of Your library as well. In both Fast-cgi and embedded server (the latter). To open topic I see no need

**Comment by silvioprog** [comment]
Awesome news! Could you test it using this [new broker](https://github.com/silvioprog/brookframework/blob/v4.0.0/brokers/Tardigrade/brooktardigradebroker.pas)? If so, it would be nice (if you agree) to publish your solution as a Brook plugin. What do you think? About the topic, feel free to ask via issues, but there is a Brook community that can be used to share this discussion with other members [here](https://plus.google.com/u/0/communities/101133820055678331036) (please send your e-mail -- Gmail -- I send the invite link for you :+1: ).

**Comment by silvioprog** [comment]
@Al-Muhandis , I have an idea. What do you think about to add a new wiki page called `Plugins/Extra` containing projects [like this](https://github.com/Al-Muhandis/brook-telegram)? :-)

**Comment by Al-Muhandis** [comment]
That's fine with me. In principle, you can even move the repository to the BrookFramework _plugins_ folder. But I don't test it in BF 5.0

**Comment by Al-Muhandis** [comment]
So, I tested tardigrade (BF 4.0). This plugin works with legacy app via tardigrade very well too

**Comment by silvioprog** [comment]
@Al-Muhandis thanks for testing and sharing it. A new page as added containing the project: https://github.com/silvioprog/brookframework/wiki/Third-party-plugins-solutions .
