### ISSUE TITLE
libbrook.pas in Source

### ISSUE THREAD

**Issue by TheEditor** [silvioprog/brookframework#153]
Line 230, the function return type gives an "identifier not found" message when compiling under Lazarus. Perhaps the line should read "bk_httpread_end: function(err: cbool): cssize_t; cdecl;"?

**Comment by silvioprog** [comment]
Hello @TheEditor . Could you provide your FPC version and which project you are trying to compile?

**Comment by TheEditor** [comment]
Silvio,

Hi! I'm using FPC 3.0.4, and I was trying to compile BrookHTTPServer. Its
just a little typo. I changed "ssize_t" to "cssize_t" and the project
worked just fine.

Thought I should stop bugging you via email. ;)

Dave Fobare

**Comment by silvioprog** [comment]
Applied: https://github.com/silvioprog/brookframework/commit/ec1c9428656432200904b86143233e3a513f6744 . :sunglasses: Thanks for reporting/fixing and feel free to contact me via e-mail too!
