### ISSUE TITLE
Server requirements?

### ISSUE THREAD

**Issue by MB34** [silvioprog/brookframework#155]
What are the requirements and how do you get your server to run the cgi applications created?

I am running WAMP, is that acceptable or do I have to use IIS?

**Comment by silvioprog** [comment]
Hello @MB34 . I'm not WAMP expert, but you can use your application in any HTTP server that supports CGI scripts. Just generate your executable and put it into the WAMP's CGI script directory. This link may help you about the required configuration: https://www.experts-exchange.com/questions/25061088/WAMP-Server-and-CGI.html .

**Comment by MFernstrom** [comment]
WAMP is a PHP stack, to use Brook with it you'd have to modify the Apache setup for it.

**Comment by silvioprog** [comment]
Closing because it seems the problem was solve. Thank you!
