### ISSUE TITLE
CPU Activity is high for tardigrade projects BROOK4

### ISSUE THREAD

**Issue by daecccp** [silvioprog/brookframework#161]
Steps to reproduce:
    1. ​Open project brookframework-4.0.0/demos/tardigrade/project1.lpi in Lazarus
    2. Build
    3. Run /brookframework-4.0.0/demos/tardigrade$ ./project1 or Start Lazarus Debug
    4. CPU Activity of one logical processor is about 100%

Same behaviour on Windows 10 64 bit (4 CPU) Lazarus 1.8.4
or VirtualBox - Linux Mint 19 32 bit – (2 CPU) Lazarus 2.0.0RC2
HP laptop, Intel Core i5-6300U
![laz_debug_tardigrade](https://user-images.githubusercontent.com/45200496/48851207-87559400-edbb-11e8-9c84-c001b17de693.png)

**Comment by silvioprog** [comment]
Thanks for reporting @daecccp .

Confirmed. It uses 13% (that is high too) in my OS (Xubuntu 18.04).

**Comment by daecccp** [comment]
This issue is solved. Tested on Windows / Linux.
Thank you!

**Comment by silvioprog** [comment]
You're welcome dude! :smiley:
