### ISSUE TITLE
Can't get POST request data

### ISSUE THREAD

**Issue by Al-Muhandis** [silvioprog/brookframework#163]
Can't get POST request data.
``` Pascal
procedure TWebhookAction.Post;
var
  Msg: String; 
begin
  PostData:=HttpRequest.Content; // PostData is empty string!
... ... ...
```
Legacy app 4.0.0 with tardigrade. Debian. Post data is not fields, that is string JSON Data.
Before with THTTPDaemonBroker worked

**Comment by silvioprog** [comment]
Hello @Al-Muhandis . I'm not sure about you are using in the client-side, but it seems you just need to inform the content-type. For example, if you are using fphttpclient (FPC) or NetHTTPClient (Delphi), just:

```delphi
YourClient.ContentType := 'application/json';
```

**Comment by silvioprog** [comment]
Additional info (that will be documented soon):

* `ARequest.IsPost` = check if the HTTP method is `POST`, `PUT`, `DELETE` or `OPTIONS`.
* `ARequest.IsUploading` = check if the client is sending data (HTML fields, payload data or uploaded files etc.) to the server.

**Comment by Al-Muhandis** [comment]
> 
> 
> Hello @Al-Muhandis . I'm not sure about you are using in the client-side, but it seems you just need to inform the content-type. For example, if you are using fphttpclient (FPC) or NetHTTPClient (Delphi), just:
> 
> ```pascal
> YourClient.ContentType := 'application/json';
> ```

1. Thank you, but I can not access the client, as it is a telegram server, and my webhook on my server, which listens to POST requests from the telegram API
2. Yes, and the content type of the request it put up correctly. It is application/json. I checked.

**Comment by Al-Muhandis** [comment]
The procedure I have is performed inside the POST method, so it is unlikely there will be another. But in any case, I don't know where are is `ARequest`? There is a property `HTTPRequest` in `TBrookAction`, and  `HTTPRequest` which does not contain these functions

**Comment by silvioprog** [comment]
Could you test it outside the webhook using `curl --header "Content-Type: application/json" --request POST --data '{"abc":123}' -w "\n" http://your-host:<your-port>`? Just to check if the problem is related to Brook or the environment.

**Comment by silvioprog** [comment]
> The procedure I have is performed inside the POST method, so it is unlikely there will be another.

Good news: you can use any HTTP method in the Tardigrade broker. :-)

> But in any case, I don't know where is a ARequest?

They are available in the request object of Brook 5+, however, in legacy apps, you can debug to check if `IsPost` is returning `True` [here](https://github.com/silvioprog/brookframework/blob/v4.0.0/brokers/Tardigrade/brooktardigradebroker.pas#L259).

I've tested all features before releasing v4.0.0, but I'll retest them again tonight.

**Comment by Al-Muhandis** [comment]
> 
> 
> Could you test it outside the webhook using `curl --header "Content-Type: application/json" --request POST --data '{"abc":123}' -w "\n" http://your-host:<your-port>`? Just to check if the problem is related to Brook or the environment.

The same... Empty POST data in the request

**Comment by silvioprog** [comment]
Confirmed. I'm going to check it tonight and provide a patch fixing the problem. Thanks for reporting!

**Comment by silvioprog** [comment]
@Al-Muhandis , could you try this attached experimental patch? To apply it, download Brook [here](https://github.com/silvioprog/brookframework/archive/v4.0.0.tar.gz), the patch [0001](https://github.com/silvioprog/brookframework/releases/download/v4.0.0/0001-Removes-redundant-configuration.patch) and [0002](https://github.com/silvioprog/brookframework/releases/download/v4.0.0/0002-Fix-issue-161-high-CPU-activity-in-Tardigrade-based-.patch), and:

```bash
git apply 0001-Removes-redundant-configuration.patch
git apply 0002-Fix-issue-161-high-CPU-activity-in-Tardigrade-based-.patch
git apply 0003-Fix-issue-163-reported-by-Al-Muhandis.patch.txt
```
and rebuild your application again to test if it works.

It is experimental, but should work well.

[0003-Fix-issue-163-reported-by-Al-Muhandis.patch.txt](https://github.com/silvioprog/brookframework/files/2626244/0003-Fix-issue-163-reported-by-Al-Muhandis.patch.txt)

**Comment by Al-Muhandis** [comment]
> 
> 
> @Al-Muhandis , could you try this attached experimental patch? To apply it, download Brook [here](https://github.com/silvioprog/brookframework/archive/v4.0.0.tar.gz), the patch [0001](https://github.com/silvioprog/brookframework/releases/download/v4.0.0/0001-Removes-redundant-configuration.patch) and [0002](https://github.com/silvioprog/brookframework/releases/download/v4.0.0/0002-Fix-issue-161-high-CPU-activity-in-Tardigrade-based-.patch), so:
> 
> ```shell
> git apply 0001-Removes-redundant-configuration.patch
> git apply 0002-Fix-issue-161-high-CPU-activity-in-Tardigrade-based-.patch
> git apply 0003-Fix-issue-163-reported-by-Al-Muhandis.patch.txt
> ```
> 
> and rebuild your application again to test if it works.
> 
> It is experimental, but should work well.
> 
> [0003-Fix-issue-163-reported-by-Al-Muhandis.patch.txt](https://github.com/silvioprog/brookframework/files/2626244/0003-Fix-issue-163-reported-by-Al-Muhandis.patch.txt)

Thank You very much! I applied the 2nd patch even earlier. 3nd patch just now. Now everything works!

**Comment by Al-Muhandis** [comment]
So now I can clarify that telegram plugin does not work with tardigrade broker without 3-nd patch for BF 4.0

**Comment by silvioprog** [comment]
Indeed. Tonight I'm going to do some tests and move this patch to [here](https://github.com/silvioprog/brookframework/releases). :-)

**Comment by silvioprog** [comment]
> Tonight I'm going to do some tests and move this patch to [here](https://github.com/silvioprog/brookframework/releases).

Done! Thanks @Al-Muhandis ! :smiley:
