### ISSUE TITLE
Where did the captcha plugin for 4.0 go?

### ISSUE THREAD

**Issue by Al-Muhandis** [silvioprog/brookframework#166]
I'm not finding it [here](https://github.com/silvioprog/brookframework/tree/v4.0.0/plugins). But just remember that it was

**Comment by silvioprog** [comment]
Strange this plugin missing from sources. 🤔 Maybe some security issue, cause it contains compiled binaries in the `3rdparty` folder. Anyway, I attached the package to the releases page, please download it [here](https://github.com/silvioprog/brookframework/releases/tag/v4.0.0) and thanks for reporting!
