### ISSUE TITLE
Some suggestion about JTemplate?

### ISSUE THREAD

**Issue by Al-Muhandis** [silvioprog/brookframework#167]
Hi @silvioprog !
What do you think about adding some rtti function to the `JTemplate` plugin? I use a small function that makes it easier to work with JTemplate, which automatically adds the `published` properties of any object along with its values to the fields of the jtemplate parser. An example can be seen in the attachment.

[0006-Some-rtti-usefull-function.-Add-published-values-to-.patch.txt](https://github.com/silvioprog/brookframework/files/2755194/0006-Some-rtti-usefull-function.-Add-published-values-to-.patch.txt)

**Comment by silvioprog** [comment]
Hello @Al-Muhandis , thanks for implementing and sorry for late answer. I'm on a travel and couldn't apply the patch to test it yet, but I took a look at its source and it seems an interesting feature. Congratulations! :-) 

After this issue I have an idea issued [here](https://github.com/silvioprog/brookframework/issues/168). If you agree, after the new repository is done, the `0006-Some-rtti-usefull-function.-Add-published-values-to-.patch` could be pushed directly as commit. :-)

What do you thin?

**Comment by silvioprog** [comment]
Applied in https://github.com/risoflora/brookfreepascal/commit/c9fd6b1cef23379f0580896298d22d5217165e25 . Thanks for contributing! :+1:
