### ISSUE TITLE
EBrookHTTPServer: Failed to send data in request for

### ISSUE THREAD

**Issue by Al-Muhandis** [silvioprog/brookframework#169]
Hi @silvioprog !
BrookFramework 4.0 with sagui (legacy), http standalone server.
It is a question. How to handle this error?
```
Exception at 05279DA0: EBrookHTTPServer:
Failed to send data in request for `/someactionpage'.
```
I often have such errors on one of my projects with webhook. Today I noticed another more simple example with this errors and it is tested on local computer and debian web server:
For example, if you attach Ajax request (for click counting) to an anchor (`<a></a>`) click event, then there will be a similar error. That is, if the script make a delay before the direct jump to a new page, the error does not occur, but then the browser will try to read the Ajax response (although in my particular case it is not necessary), if the delay is removed, then the server has a similar error.

Simply I assume that a similar error occurs when the client does not read the server response for some reason. This situation may arise. How to process this request correctly? Could there be a memoryleak for this reason?

**Comment by silvioprog** [comment]
Hello @Al-Muhandis , could you move this issue to [risoflora/brookframework/issues](https://github.com/risoflora/brookframework/issues)? This repository is going to be archived and redirected to [risoflora/brookfreepascal](https://github.com/risoflora/brookfreepascal). Thank you!

**Comment by Al-Muhandis** [comment]
Ok!
