### ISSUE TITLE
If Mustache  for Delphi is ported to FPC it'll be must be helpful

### ISSUE THREAD

**Issue by edwinyzh** [silvioprog/brookframework#91]
Hi, just a suggestion, Mr. Arnaud BOUCHEZ has just released an open sourced Delphi implementation of the Mustache logic-less template engine, it must be help to brook users if it's ported to FPC. Just a suggestion, I've not got a chance to use brook yet, but it's absolutely an amazing web framework!

https://forums.embarcadero.com/thread.jspa?threadID=104015

**Comment by silvioprog** [comment]
The new version of Brook (that will be released soon) implements on its controllers a new concept of view adapter and body parser, so you could use any external lexer/parser/(de)multiplexer/(de)compressor/conversor as a default body or payload in your controller.
