### ISSUE TITLE
Unnecessary #13#10 after the response text.

### ISSUE THREAD

**Issue by spamcampus** [silvioprog/brookframework#93]
Unnecessary #13#10 after the response text in BrookStaticFileBroker
For most situation of generating dynamic html text, unnecessary #13#10 after the contents are nothing harm. However, when you handle a file and send it to the client, it is serious issue.
Since TResponse.Content is TString and BrookAction Write function uses it what every anything happens. #13#10 is tag along right after the content. Unnecessary 2 byte of information goes to the client.

**Comment by silvioprog** [comment]
Please open a new issue for FCL team about this bug if it persists.
